version: "3.7"

services:
  scala:
    container_name: scala
    build:
      context: ./
      dockerfile: ./docker/scala/Dockerfile
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - ./logs:/isis-to-mongodb/logs
      - ./export:/isis-to-mongodb/export
    links:
    - mongodb
    depends_on:
    - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:6.0.2
    environment:
    - PUID=1000
    - PGID=1000
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root
    - MONGO_INITDB_DATABASE=isismongodb
    volumes:
      - ./data/mongodb:/data/db
    ports:
    - 27017:27017
    restart: always

  mongodb-seed:
    build: 
      context: ./
      dockerfile: ./docker/mongodb-seed/Dockerfile
    depends_on:
      - mongodb